# ConfigMap to store USERSTORE_HOST variable in
# --------------------
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: userapi-config
  labels:
    data: config1
data:
  userstore_host: "NOTSET"
---