version: "3.8"
services:
  movieapi:
    image: service1-movieapi
    ports:
      - 9000:4000
    volumes:
      - ./Service1-MovieAPI:/app/
    environment:
      TEXTSTORE_HOST: textstore
      TIMEOUT: 10

  userauth:
    image: service2-userauth
    ports:
    - 9001:4001
    volumes:
      - ./Service2-UserAuth:/app/src
    deploy:
      replicas: 1
    environment:
      TEXTSTORE_HOST: textstore

  textstore:
    image: mongo
    restart: always
    command: --quiet --syslog
    ports:
    - 27017:9000
    volumes:
      - textstore-data:/data/db
      - mongo-config:/data/configdb

volumes:
  textstore-data:
  mongo-config:

