version: "3.8"
services:
  movieapi:
    image: movieapi:latest
    ports:
      - 5004:5004
    volumes:
      - ./movieAPI:/app/
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/movieapp
    depends_on:
      - mongodb

  userapi:
    image: userapi:latest
    ports:
      - 5005:5005
    volumes:
      - "./userAPI:/app/"
      - /app/node_modules/
    deploy:
      replicas: 1
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/user
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    command: --quiet --syslog
    expose:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - mongo-config:/data/configdb

volumes:
  mongodb-data:
  mongo-config:
