apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userapi-ingress
  namespace: default
spec:
  rules:
  - host: userapi.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: userapi-service
            port:
              number: 5005
  - host: movieapi.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: movieapi-service
            port:
              number: 5004
