# Userapi
# --------------------
# - Deployment to launch one container of shoebhashem/userapi:v4 in a pod.
# - Service (type: LoadBalancer) to open up the app to the world (localhost, at least).
# 
---
apiVersion: v1
kind: Secret
metadata:
  name: session-secret
type: Opaque
data:
  SESSION_SECRET: cmFuZG9tLXNlY3JldC1rZXk= 
---
apiVersion: v1
kind: Service
metadata:
  name: userapi-service
  labels:
    app: userapi
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5005
    targetPort: 5005
    protocol: TCP
  selector:
    app: userapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  labels:
    app: userapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
      - name: userapi
        image: shoebhashem/userapi:v10
        ports:
        - containerPort: 5005
        env:
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: SESSION_SECRET 

        - name: USERSTORE_HOST
          valueFrom:
            configMapKeyRef:
              name: userapi-config
              key: userstore_host
        - name: MOVIE_API_URL  
          value: "user.movieapi.com/movies"  # Set the URL to the name of your movie service

---
# UextStore
# --------------------c
# - one container per pod running the image mongodb
# - one headless service to access them.
# - Two persistentVolumeClaims/mounts: textstore-data, and mongo-config
---
apiVersion: v1
kind: Service
metadata:
  name: userstore-service
  labels:
    app: userstore
spec:
  ports:
  - port: 27017
    targetPort: mongodb-port
  selector:
    app: userstore
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: userstore
  labels:
    app: userstore
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: userstore
  template:
    metadata:
      labels:
        app: userstore
    spec:
      containers:
      - name: userstore
        image: mongo
        ports:
        - containerPort: 27017
          name: mongodb-port
        volumeMounts:
        - name: userstore-data
          mountPath: /data/db
        - name: mongo-config
          mountPath: /data/configdb
  volumeClaimTemplates:
    - metadata:
        name: userstore-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Mi
    - metadata:
        name: mongo-config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Mi
---
# ConfigMap to store USERSTORE_HOST variable in
# --------------------
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: userapi-config
  labels:
    data: config
data:
  userstore_host: "NOTSET"
  MOVIE_API_URL: "user.movieapi.com/movies"  # Add this line with the URL
  #MOVIE_APP_PORT: "5004"  # Add this line with the port
---

